version: "3"

services:

  server:

    image: beonewithyuri/server:1.0.0
 
    build: 
      context: server/
      network: host

    ports:
      - 8000:8000

    user: "1001"

    network_mode: host

    healthcheck:
        test: wget --no-verbose --tries=1 --spider http://localhost:8000 || exit 1
        interval: 5s
        timeout: 5s
        retries: 5

  client:

    image: beonewithyuri/client:1.0.0

    build: 
      context: client/

    user: "1001"

    network_mode: host

    command: "python ./client.py"

    depends_on:
      server:
        condition: service_healthy