apiVersion: v1
kind: Pod
metadata:
  labels:
    test: startup
  name: startup
spec:
  containers:
  - name: startup
    image: k8s.gcr.io/liveness
    args:
    - /server
    ports:
    - containerPort: 8080
      name: serverport
    startupProbe:
      httpGet:
        path: /started
        port: serverport
      failureThreshold: 10
      periodSeconds: 5
    readinessProbe:
      tcpSocket:
        port: serverport
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: serverport
      initialDelaySeconds: 15
      periodSeconds: 20